var annotated_dup =
[
    [ "Botography", "namespace_botography.html", [
      [ "Dependencies", "namespace_botography_1_1_dependencies.html", [
        [ "Interfaces", "namespace_botography_1_1_dependencies_1_1_interfaces.html", [
          [ "IManager", "interface_botography_1_1_dependencies_1_1_interfaces_1_1_i_manager.html", "interface_botography_1_1_dependencies_1_1_interfaces_1_1_i_manager" ],
          [ "ISystem", "interface_botography_1_1_dependencies_1_1_interfaces_1_1_i_system.html", null ],
          [ "IUiCollection", "interface_botography_1_1_dependencies_1_1_interfaces_1_1_i_ui_collection.html", "interface_botography_1_1_dependencies_1_1_interfaces_1_1_i_ui_collection" ],
          [ "IUiElement", "interface_botography_1_1_dependencies_1_1_interfaces_1_1_i_ui_element.html", "interface_botography_1_1_dependencies_1_1_interfaces_1_1_i_ui_element" ]
        ] ],
        [ "ManagerBase", "class_botography_1_1_dependencies_1_1_manager_base.html", "class_botography_1_1_dependencies_1_1_manager_base" ],
        [ "SystemBase", "class_botography_1_1_dependencies_1_1_system_base.html", null ],
        [ "UiCollectionBase", "class_botography_1_1_dependencies_1_1_ui_collection_base.html", "class_botography_1_1_dependencies_1_1_ui_collection_base" ]
      ] ],
      [ "Lab", "namespace_botography_1_1_lab.html", [
        [ "LabManager", "class_botography_1_1_lab_1_1_lab_manager.html", null ],
        [ "LabSystem", "class_botography_1_1_lab_1_1_lab_system.html", null ],
        [ "LabUiCollection", "class_botography_1_1_lab_1_1_lab_ui_collection.html", null ]
      ] ],
      [ "Map", "namespace_botography_1_1_map.html", [
        [ "MapManager", "class_botography_1_1_map_1_1_map_manager.html", null ],
        [ "QuadrantSO", "class_botography_1_1_map_1_1_quadrant_s_o.html", null ],
        [ "RegionSO", "class_botography_1_1_map_1_1_region_s_o.html", null ],
        [ "SectorSO", "class_botography_1_1_map_1_1_sector_s_o.html", null ],
        [ "SolidSectorSO", "class_botography_1_1_map_1_1_solid_sector_s_o.html", null ],
        [ "SplitSectorSO", "class_botography_1_1_map_1_1_split_sector_s_o.html", null ]
      ] ],
      [ "Notifications", "namespace_botography_1_1_notifications.html", [
        [ "Notification", "class_botography_1_1_notifications_1_1_notification.html", null ],
        [ "Notifyer", "class_botography_1_1_notifications_1_1_notifyer.html", null ]
      ] ],
      [ "OverworldInteraction", "namespace_botography_1_1_overworld_interaction.html", [
        [ "OWIManager", "class_botography_1_1_overworld_interaction_1_1_o_w_i_manager.html", null ]
      ] ],
      [ "Player", "namespace_botography_1_1_player.html", [
        [ "Dialogue", "namespace_botography_1_1_player_1_1_dialogue.html", [
          [ "AsyncDialogueSO", "class_botography_1_1_player_1_1_dialogue_1_1_async_dialogue_s_o.html", null ],
          [ "ConvoSO", "class_botography_1_1_player_1_1_dialogue_1_1_convo_s_o.html", "class_botography_1_1_player_1_1_dialogue_1_1_convo_s_o" ],
          [ "DialogueDatabaseSO", "class_botography_1_1_player_1_1_dialogue_1_1_dialogue_database_s_o.html", null ],
          [ "DialoguePlayer", "class_botography_1_1_player_1_1_dialogue_1_1_dialogue_player.html", null ],
          [ "DialogueSO", "class_botography_1_1_player_1_1_dialogue_1_1_dialogue_s_o.html", null ],
          [ "SyncDialogueSO", "class_botography_1_1_player_1_1_dialogue_1_1_sync_dialogue_s_o.html", null ]
        ] ],
        [ "StatusEffects", "namespace_botography_1_1_player_1_1_status_effects.html", [
          [ "PosStatusEffect", "class_botography_1_1_player_1_1_status_effects_1_1_pos_status_effect.html", "class_botography_1_1_player_1_1_status_effects_1_1_pos_status_effect" ],
          [ "StatusEffect", "class_botography_1_1_player_1_1_status_effects_1_1_status_effect.html", null ],
          [ "StatusEffectsHandler", "class_botography_1_1_player_1_1_status_effects_1_1_status_effects_handler.html", null ],
          [ "Temperature", "class_botography_1_1_player_1_1_status_effects_1_1_temperature.html", null ],
          [ "TimedStatusEffect", "class_botography_1_1_player_1_1_status_effects_1_1_timed_status_effect.html", "class_botography_1_1_player_1_1_status_effects_1_1_timed_status_effect" ]
        ] ],
        [ "PlayerConstants", "class_botography_1_1_player_1_1_player_constants.html", null ],
        [ "PlayerManager", "class_botography_1_1_player_1_1_player_manager.html", null ],
        [ "PlayerSystem", "class_botography_1_1_player_1_1_player_system.html", null ],
        [ "PlayerUiCollection", "class_botography_1_1_player_1_1_player_ui_collection.html", null ]
      ] ],
      [ "UIGeneric", "namespace_botography_1_1_u_i_generic.html", [
        [ "TextElement", "class_botography_1_1_u_i_generic_1_1_text_element.html", "class_botography_1_1_u_i_generic_1_1_text_element" ]
      ] ]
    ] ],
    [ "AlmanacManager", "class_almanac_manager.html", null ],
    [ "AlmanacPanaceanPlantDiscovered", "class_almanac_panacean_plant_discovered.html", null ],
    [ "AlmanacPlantDiscovered", "class_almanac_plant_discovered.html", null ],
    [ "AlmanacSystem", "class_almanac_system.html", null ],
    [ "AlmanacToggle", "class_almanac_toggle.html", null ],
    [ "AlmanacUI", "class_almanac_u_i.html", null ],
    [ "AnchorDraggable", "class_anchor_draggable.html", null ],
    [ "BasePlant", "class_base_plant.html", null ],
    [ "BaseStatTile", "class_base_stat_tile.html", null ],
    [ "BeanstalkAnchor", "class_beanstalk_anchor.html", null ],
    [ "BeanstalkPlant", "class_beanstalk_plant.html", null ],
    [ "BubblePlant", "class_bubble_plant.html", null ],
    [ "CameraManager", "class_camera_manager.html", null ],
    [ "ColorConstants", "class_color_constants.html", null ],
    [ "Comment", "class_comment.html", null ],
    [ "ConsumptionManager", "class_consumption_manager.html", null ],
    [ "CoyoteTime", "class_coyote_time.html", null ],
    [ "CoyoteTimeHandler", "class_coyote_time_handler.html", "class_coyote_time_handler" ],
    [ "DraggableItem", "class_draggable_item.html", null ],
    [ "EquipmentEffectManager", "class_equipment_effect_manager.html", null ],
    [ "EquipmentPlant", "class_equipment_plant.html", null ],
    [ "EquipmentSlot", "class_equipment_slot.html", null ],
    [ "FeatureTile", "class_feature_tile.html", null ],
    [ "FernacePlant", "class_fernace_plant.html", null ],
    [ "GameConstants", "class_game_constants.html", null ],
    [ "GrowcapPlant", "class_growcap_plant.html", null ],
    [ "HandSlot", "class_hand_slot.html", null ],
    [ "IConsumable", "interface_i_consumable.html", null ],
    [ "IEquipment", "interface_i_equipment.html", null ],
    [ "IInteractivePlaceable", "interface_i_interactive_placeable.html", null ],
    [ "IInventoryItem", "interface_i_inventory_item.html", null ],
    [ "IKeyItem", "interface_i_key_item.html", null ],
    [ "InputHandler", "class_input_handler.html", null ],
    [ "InteractableObject", "class_interactable_object.html", null ],
    [ "InteractionManager", "class_interaction_manager.html", null ],
    [ "InventoryDraggable", "class_inventory_draggable.html", null ],
    [ "InventoryManager", "class_inventory_manager.html", null ],
    [ "InventorySystem", "class_inventory_system.html", null ],
    [ "InventoryUI", "class_inventory_u_i.html", null ],
    [ "InvisibleBoxOverPlayer", "class_invisible_box_over_player.html", null ],
    [ "IPlaceable", "interface_i_placeable.html", null ],
    [ "IRadiusPlaceable", "interface_i_radius_placeable.html", null ],
    [ "IRootState", "interface_i_root_state.html", null ],
    [ "Jar", "class_jar.html", null ],
    [ "LabToggler", "class_lab_toggler.html", null ],
    [ "LanternPlant", "class_lantern_plant.html", null ],
    [ "LayerTrigger", "class_layer_trigger.html", null ],
    [ "LightStatTile", "class_light_stat_tile.html", null ],
    [ "LilySlippiesPlant", "class_lily_slippies_plant.html", null ],
    [ "MacguffinBasePlant", "class_macguffin_base_plant.html", null ],
    [ "MapConstants", "class_map_constants.html", null ],
    [ "Meltable", "class_meltable.html", null ],
    [ "MenuFunctionality", "class_menu_functionality.html", null ],
    [ "MenuManagerBase", "class_menu_manager_base.html", null ],
    [ "MenuSystemBase", "class_menu_system_base.html", null ],
    [ "MenuUiCollectionBase", "class_menu_ui_collection_base.html", null ],
    [ "MirrorMossPlant", "class_mirror_moss_plant.html", null ],
    [ "MiscPrototyping", "class_misc_prototyping.html", null ],
    [ "MuchroomPlant", "class_muchroom_plant.html", null ],
    [ "NoteInteractableObject", "class_note_interactable_object.html", null ],
    [ "NoteSO", "class_note_s_o.html", null ],
    [ "ObstacleAbstract", "class_obstacle_abstract.html", null ],
    [ "OpenAndCloseMap", "class_open_and_close_map.html", null ],
    [ "OsmosisLotusPlant", "class_osmosis_lotus_plant.html", null ],
    [ "PanaceanPlantSO", "class_panacean_plant_s_o.html", null ],
    [ "PauseGame", "class_pause_game.html", null ],
    [ "PestPileObstacle", "class_pest_pile_obstacle.html", null ],
    [ "PhoenixRosePlant", "class_phoenix_rose_plant.html", null ],
    [ "PhysicalStatTile", "class_physical_stat_tile.html", null ],
    [ "PipevinePlant", "class_pipevine_plant.html", null ],
    [ "PitcherPlant", "class_pitcher_plant.html", null ],
    [ "PlacementManager", "class_placement_manager.html", null ],
    [ "PlantSO", "class_plant_s_o.html", null ],
    [ "PlayerBaseState", "class_player_base_state.html", null ],
    [ "PlayerClimbState", "class_player_climb_state.html", null ],
    [ "PlayerGroundedState", "class_player_grounded_state.html", null ],
    [ "PlayerIdleState", "class_player_idle_state.html", null ],
    [ "PlayerInteraction", "class_player_interaction.html", null ],
    [ "PlayerStateFactory", "class_player_state_factory.html", null ],
    [ "PlayerStateMachine", "class_player_state_machine.html", null ],
    [ "PlayerWalkState", "class_player_walk_state.html", null ],
    [ "Prototype_IInventoryItem", "interface_prototype___i_inventory_item.html", null ],
    [ "RecipeListSO", "class_recipe_list_s_o.html", null ],
    [ "RespawnHandler", "class_respawn_handler.html", null ],
    [ "RoseCuffsPlant", "class_rose_cuffs_plant.html", null ],
    [ "SignInteractableObject", "class_sign_interactable_object.html", null ],
    [ "Slot", "class_slot.html", null ],
    [ "SoilSlot", "class_soil_slot.html", null ],
    [ "SpearmintPlant", "class_spearmint_plant.html", null ],
    [ "StackableItem", "class_stackable_item.html", null ],
    [ "StackedSlot", "class_stacked_slot.html", null ],
    [ "StatusEffectUI", "class_status_effect_u_i.html", null ],
    [ "StellaBloomPlant", "class_stella_bloom_plant.html", null ],
    [ "TransitionManager", "class_transition_manager.html", null ],
    [ "TransitionSystem", "class_transition_system.html", null ],
    [ "TransitionUI", "class_transition_u_i.html", null ],
    [ "TrashCan", "class_trash_can.html", null ],
    [ "UIManager", "class_u_i_manager.html", null ],
    [ "UnbearableCondition", "class_unbearable_condition.html", null ],
    [ "UnderwaterManager", "class_underwater_manager.html", null ],
    [ "UnderwaterObstacle", "class_underwater_obstacle.html", null ],
    [ "WaterObstacle", "class_water_obstacle.html", null ],
    [ "WaterSlot", "class_water_slot.html", null ]
];